name: Release Node.js app

on:
  push:
    branches:
      - main

jobs:
  publish-to-docker-hub:
    name: publish to docker hub
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job start ${{github.ref}}"
      - uses: actions/checkout@v4
      - name: Login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/devopsdocker-ex-3:latest

      - name: Deploy with compose
        env:
          REPO_USER: ${{secrets.DOCKERHUB_USERNAME}}
          REPO_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
